### ISSUE TITLE
E185: Cannot find color scheme 'tomorrow'

### ISSUE THREAD

**Issue by joelremix** [co1ncidence/mountaineer.vim#19]
I see the if statement checking for base16_shell_path but I don't use base16 anymore. Could you do another type of check?

**Comment by co1ncidence** [comment]
I apologize for the inclusion of that check. I had implemented it so I could cross test my colorscheme with another one and forgot to remove those lines when pushing the changes. I have fixed the problem, if you encounter any other issues, please let me know.

**Comment by joelremix** [comment]
I still see the same error. First deleted mountaineer.vim directory then reinstalled using VimPlug
